[package]
name = "rls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bezier-nd = "0.5.0"
eframe = "0.22.0"
emath = "0.22.0"
geo-nd = "0.5.0"
paste = "1.0.12"
