[package]
name = "cuprous"
version = "0.2.0"
edition = "2024"

[dependencies]
bezier-nd = "0.5.0"
eyre = "0.6.12"
geo-nd = "0.6.0"
getrandom = "0.2.15"
glow = "0.16.0"
num-traits = "0.2.19"
parking_lot = { version = "0.12.3", features = ["arc_lock", "serde"] }
paste = "1.0.15"
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.63"

egui_dock = { version = "0.18.0", features = ["serde"] }
egui_extras = "0.33.3"

traitbox = { path = "crates/traitbox" }
base64 = "0.22.1"
flate2 = "1.1.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories-next = "2.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.117"
wasm-bindgen-futures = "0.4.67"
web-sys = "0.3.94"

[dependencies.eframe]
version = "0.33.3"
default-features = false
features = [
    "persistence",
    "default_fonts",
    "x11",
    "wayland",
    "glow",
    "accesskit",
    "web_screen_reader",
    "ron",
    "serde",
]

[dependencies.smoldata]
git = "https://github.com/Ved-s/smoldata.git"
rev = "53e54b5533b4a9745fb64c7ce6ea762b291d8e46"
features = []

[features]
wip_circuits = []
wasm = ["getrandom/js"]

[patch.crates-io.eframe]
git = "https://github.com/emilk/egui.git"
# Fork: Ved-s/egui/tree/feature/customStorage
# PR: https://github.com/emilk/egui/pull/7856
# PR PR: https://github.com/Leinnan/egui/pull/1
rev = "2d5f2099bd6c088445b6625a9084c0aa18d37136"

[patch.crates-io.egui]
git = "https://github.com/emilk/egui.git"
rev = "2d5f2099bd6c088445b6625a9084c0aa18d37136"


[patch.crates-io.egui_extras]
git = "https://github.com/emilk/egui.git"
rev = "2d5f2099bd6c088445b6625a9084c0aa18d37136"